### ISSUE TITLE
HTML output generation fails, because XsltProcessor class loading fails

### ISSUE THREAD

**Issue by jakoch** [phpbench/phpbench#435]
`php phpbench.phar run benchmarks/Compare.php --report=default --output=html`

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "XsltProcessor" from the global namespace.
Did you forget a "use" statement? in phar://C:/server_main/www/benchmark/phpbench.phar/lib/Report/Renderer/XsltRenderer.php:92
Stack trace:
#0 phar://C:/server_main/www/benchmark/phpbench.phar/lib/Report/ReportManager.php(98): PhpBench\Report\Renderer\XsltRenderer->render(Object(PhpBench\Dom\Document), Object(PhpBench\Registry\Config))
#1 phar://C:/server_main/www/benchmark/phpbench.phar/lib/Console/Command/Handler/ReportHandler.php(41): PhpBench\Report\ReportManager->renderReports(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(PhpBench\Model\SuiteCollection), Array, Array)
#2 phar://C:/server_main/www/benchmark/phpbench.phar/lib/Console/Command/RunCommand.php(97): PhpBench\Console\Command\Handler\ReportHandler->reportsFromInput(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(PhpBench\Model\SuiteC in phar://C:/server_main/www/benchmark/phpbench.phar/lib/Report/Renderer/XsltRenderer.php on line 92

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "XsltProcessor" from the global namespace.
Did you forget a "use" statement? in phar://C:/server_main/www/benchmark/phpbench.phar/lib/Report/Renderer/XsltRenderer.php:92
Stack trace:
#0 phar://C:/server_main/www/benchmark/phpbench.phar/lib/Report/ReportManager.php(98): PhpBench\Report\Renderer\XsltRenderer->render(Object(PhpBench\Dom\Document), Object(PhpBench\Registry\Config))
#1 phar://C:/server_main/www/benchmark/phpbench.phar/lib/Console/Command/Handler/ReportHandler.php(41): PhpBench\Report\ReportManager->renderReports(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(PhpBench\Model\SuiteCollection), Array, Array)
#2 phar://C:/server_main/www/benchmark/phpbench.phar/lib/Console/Command/RunCommand.php(97): PhpBench\Console\Command\Handler\ReportHandler->reportsFromInput(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(PhpBench\Model\SuiteC in phar://C:/server_main/www/benchmark/phpbench.phar/lib/Report/Renderer/XsltRenderer.php on line 92
```

**Comment by dantleech** [comment]
Hmm, well we should probably add a runtime check for the XSLT library - it is already required in `composer.json` but that doesn't help when using the PHAR.

**Comment by jakoch** [comment]
Thank you, Dan!
