### ISSUE TITLE
benchNothing return zero 

### ISSUE THREAD

**Issue by phpstatic** [phpbench/phpbench#626]
I run phpbench master branch on macOS (cpu 7700K) with php build with `gcc -Ofast`, version 7.4, 7.3, 7.2.   some time it throw this error:

```sh
    PhpBench\Benchmark\Remote\Exception\ScriptErrorException 
    Warning: Division by zero in /opt/web/bench/lib/Report/Generator/TableGenerator.php on line 154
    
    Fatal error: Uncaught InvalidArgumentException: Non-numeric value encountered: "NAN" in /opt/web/bench/lib/Formatter/Format/NumberFormat.php:22
    Stack trace:
    #0 /opt/web/bench/lib/Formatter/Formatter.php(128): PhpBench\Formatter\Format\NumberFormat->format('NAN', Array)
    #1 /opt/web/bench/lib/Report/Renderer/ConsoleRenderer.php(105): PhpBench\Formatter\Formatter->applyClasses(Array, 'NAN', Array)
    #2 /opt/web/bench/lib/Report/Renderer/ConsoleRenderer.php(77): PhpBench\Report\Renderer\ConsoleRenderer->renderTableElement(Object(PhpBench\Dom\Element), Object(PhpBench\Registry\Config))
    #3 /opt/web/bench/lib/Report/ReportManager.php(106): PhpBench\Report\Renderer\ConsoleRenderer->render(Object(PhpBench\Dom\Document), Object(PhpBench\Registry\Config))
    #4 /opt/web/bench/lib/Console/Command/Handler/ReportHandler.php(47): PhpBench\Report\ReportManager->renderReports(Object(Symfony\Component\Console\Output\BufferedOutput), Object(PhpBench\Model\SuiteCollection), Array, Array)
    #5 /opt/web/bench/lib/Console/Command/ReportCommand.php(87) in /opt/web/bench/lib/Formatter/Formatter.php on line 131
    

    #0 /opt/web/bench/lib/Executor/Benchmark/TemplateExecutor.php(74): PhpBench\Benchmark\Remote\Payload->launch()
    #1 /opt/web/bench/lib/Executor/Benchmark/TemplateExecutor.php(62): PhpBench\Executor\Benchmark\TemplateExecutor->launch(Object(PhpBench\Benchmark\Remote\Payload), Object(PhpBench\Model\Iteration), Object(PhpBench\Registry\Config))
    #2 /opt/web/bench/lib/Executor/CompositeExecutor.php(46): PhpBench\Executor\Benchmark\TemplateExecutor->execute(Object(PhpBench\Benchmark\Metadata\SubjectMetadata), Object(PhpBench\Model\Iteration), Object(PhpBench\Registry\Config))
    #3 /opt/web/bench/lib/Benchmark/Runner.php(344): PhpBench\Executor\CompositeExecutor->execute(Object(PhpBench\Benchmark\Metadata\SubjectMetadata), Object(PhpBench\Model\Iteration), Object(PhpBench\Registry\Config))
    #4 /opt/web/bench/lib/Benchmark/Runner.php(290): PhpBench\Benchmark\Runner->runIteration(Object(PhpBench\Executor\CompositeExecutor), Object(PhpBench\Registry\Config), Object(PhpBench\Model\Iteration), Object(PhpBench\Benchmark\Metadata\SubjectMetadata))
    #5 /opt/web/bench/lib/Benchmark/Runner.php(265): PhpBench\Benchmark\Runner->runVariant(Object(PhpBench\Executor\CompositeExecutor), Object(PhpBench\Registry\Config), Object(PhpBench\Benchmark\RunnerConfig), Object(PhpBench\Benchmark\Metadata\SubjectMetadata), Object(PhpBench\Model\Variant))
    #6 /opt/web/bench/lib/Benchmark/Runner.php(199): PhpBench\Benchmark\Runner->runSubject(Object(PhpBench\Executor\CompositeExecutor), Object(PhpBench\Benchmark\RunnerConfig), Object(PhpBench\Model\Subject), Object(PhpBench\Benchmark\Metadata\SubjectMetadata))
    #7 /opt/web/bench/lib/Benchmark/Runner.php(131): PhpBench\Benchmark\Runner->runBenchmark(Object(PhpBench\Benchmark\RunnerConfig), Object(PhpBench\Model\Benchmark), Object(PhpBench\Benchmark\Metadata\BenchmarkMetadata))
    #8 /opt/web/bench/lib/Console/Command/Handler/RunnerHandler.php(94): PhpBench\Benchmark\Runner->run('/opt/web/bench/...', Object(PhpBench\Benchmark\RunnerConfig))
    #9 /opt/web/bench/lib/Console/Command/RunCommand.php(112): PhpBench\Console\Command\Handler\RunnerHandler->runFromInput(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(PhpBench\Benchmark\RunnerConfig))
    #10 /opt/web/bench/vendor/symfony/console/Command/Command.php(255): PhpBench\Console\Command\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #11 /opt/web/bench/vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #12 /opt/web/bench/vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(PhpBench\Console\Command\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #13 /opt/web/bench/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #14 /opt/web/bench/lib/PhpBench.php(60): Symfony\Component\Console\Application->run()
    #15 /opt/web/bench/bin/phpbench.php(23): PhpBench\PhpBench::run(Object(Composer\Autoload\ClassLoader))
    #16 /opt/web/bench/bin/phpbench(4): require('/opt/web/bench/...')
    #17 {main}
```

and some time get report like this:

```sh
PhpBench @git_tag@. Running benchmarks.
Using configuration file: /opt/web/bench/phpbench.json.dist

\PhpBench\Benchmarks\Micro\HashingBench

    benchAlgos # 0..........................I9 [μ Mo]/r: 0.193 0.183 (μs) [μSD μRSD]/r: 0.030μs 15.48%
    benchAlgos # 1..........................I9 [μ Mo]/r: 0.372 0.373 (μs) [μSD μRSD]/r: 0.002μs 0.46%

\PhpBench\Micro\Math\KdeBench

    benchKde # ten points...................I9 [μ Mo]/r: 0.0237 0.0227 (ms) [μSD μRSD]/r: 0.001ms 6.01%
    benchKde # twenty points................I9 [μ Mo]/r: 0.0398 0.0392 (ms) [μSD μRSD]/r: 0.002ms 4.72%
    benchKde # forty points.................I9 [μ Mo]/r: 0.0697 0.0696 (ms) [μSD μRSD]/r: 0.002ms 3.31%

\PhpBench\Micro\Math\StatisticsBench

    benchVariance...........................I9 [μ Mo]/r: 0.65 0.62 (μs) [μSD μRSD]/r: 0.091μs 13.94%
    benchStDev..............................I9 [μ Mo]/r: 0.71 0.66 (μs) [μSD μRSD]/r: 0.160μs 22.50%

\PhpBench\Benchmarks\Micro\DependencyInjection\ContainerBench

    benchInitNoExtensions...................I9 [μ Mo]/r: 0.000035 0.000033 (s) [μSD μRSD]/r: 0.000s 12.07%
    benchInitCoreExtension..................I9 [μ Mo]/r: 0.000242 0.000236 (s) [μSD μRSD]/r: 0.000s 5.14%

\PhpBench\Benchmarks\Macro\LogBench

    benchLog................................I9 [μ Mo]/r: 0.010 0.010 (s) [μSD μRSD]/r: 0.000s 1.93%

\PhpBench\Benchmarks\Macro\benchmarks\NothingBench

    benchNothing............................I0 [μ Mo]/r: 0.000 0.000 (μs) [μSD μRSD]/r: 0.000μs 0.00%

\PhpBench\Benchmarks\Macro\RunBench

    benchRun................................I9 [μ Mo]/r: 0.116 0.116 (s) [μSD μRSD]/r: 0.002s 1.34%
    benchRunAndReport.......................I9 [μ Mo]/r: 0.117 0.116 (s) [μSD μRSD]/r: 0.002s 1.51%

\PhpBench\Benchmarks\Macro\ReportBench

    benchAggregate..........................I9 [μ Mo]/r: 0.002 0.002 (s) [μSD μRSD]/r: 0.000s 3.88%
    benchDefault............................I9 [μ Mo]/r: 0.002 0.002 (s) [μSD μRSD]/r: 0.000s 9.63%
    benchEnv................................I9 [μ Mo]/r: 0.002 0.002 (s) [μSD μRSD]/r: 0.000s 4.34%

13 subjects, 151 iterations, 2,527 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 0.000 [15,595.400 15,500.326] 0.000 (μs)
⅀T: 2,495,264.073μs μSD/r 244.596μs μRSD/r: 6.641%
```

**Comment by dantleech** [comment]
Assume this is master? The build is currently failing because of this.

**Comment by dantleech** [comment]
Should be fixed now

**Comment by phpstatic** [comment]
I test on master yesterday, and just retest it with updated master branch.  no more exception anymore.

But I am not sure I understand this result correct:  `(best [mean mode] worst) = 0.000 [14,982.407 14,962.102] 0.000 (μs)`,  why the worst value still be 0.000 ?


```sh
\PhpBench\Benchmarks\Micro\HashingBench

    benchAlgos # 0..........................I9 [μ Mo]/r: 0.190 0.190 (μs) [μSD μRSD]/r: 0.002μs 0.95%
    benchAlgos # 1..........................I9 [μ Mo]/r: 0.397 0.396 (μs) [μSD μRSD]/r: 0.003μs 0.70%

\PhpBench\Micro\Math\KdeBench

    benchKde # ten points...................I9 [μ Mo]/r: 0.0229 0.0228 (ms) [μSD μRSD]/r: 0.000ms 1.25%
    benchKde # twenty points................I9 [μ Mo]/r: 0.0402 0.0393 (ms) [μSD μRSD]/r: 0.002ms 5.93%
    benchKde # forty points.................I9 [μ Mo]/r: 0.0744 0.0696 (ms) [μSD μRSD]/r: 0.007ms 9.86%

\PhpBench\Micro\Math\StatisticsBench

    benchVariance...........................I9 [μ Mo]/r: 0.68 0.69 (μs) [μSD μRSD]/r: 0.021μs 3.06%
    benchStDev..............................I9 [μ Mo]/r: 0.71 0.70 (μs) [μSD μRSD]/r: 0.044μs 6.15%

\PhpBench\Benchmarks\Micro\DependencyInjection\ContainerBench

    benchInitNoExtensions...................I9 [μ Mo]/r: 0.000031 0.000031 (s) [μSD μRSD]/r: 0.000s 1.38%
    benchInitCoreExtension..................I9 [μ Mo]/r: 0.000228 0.000227 (s) [μSD μRSD]/r: 0.000s 1.39%

\PhpBench\Benchmarks\Macro\LogBench

    benchLog................................I9 [μ Mo]/r: 0.010 0.010 (s) [μSD μRSD]/r: 0.000s 1.12%

\PhpBench\Benchmarks\Macro\benchmarks\NothingBench

    benchNothing............................I0 [μ Mo]/r: 0.000 0.000 (μs) [μSD μRSD]/r: 0.000μs 0.00%

\PhpBench\Benchmarks\Macro\RunBench

    benchRun................................I9 [μ Mo]/r: 0.111 0.111 (s) [μSD μRSD]/r: 0.001s 0.68%
    benchRunAndReport.......................I9 [μ Mo]/r: 0.112 0.112 (s) [μSD μRSD]/r: 0.001s 0.63%

\PhpBench\Benchmarks\Macro\ReportBench

    benchAggregate..........................I9 [μ Mo]/r: 0.002 0.002 (s) [μSD μRSD]/r: 0.000s 3.67%
    benchDefault............................I9 [μ Mo]/r: 0.002 0.002 (s) [μSD μRSD]/r: 0.000s 3.37%
    benchEnv................................I9 [μ Mo]/r: 0.002 0.002 (s) [μSD μRSD]/r: 0.000s 4.77%

13 subjects, 151 iterations, 2,527 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 0.000 [14,982.407 14,962.102] 0.000 (μs)
⅀T: 2,397,185.080μs μSD/r 113.679μs μRSD/r: 2.806%
```

**Comment by dantleech** [comment]
> But I am not sure I understand this result correct: (best [mean mode] worst) = 0.000 [14,982.407 14,962.102] 0.000 (μs), why the worst value still be 0.000 ?

:thinking: not sure tbh. But `0` is not a valid measurement - and if somebody were to have a `0` then they should increase the revs to actually get a meaningful number.

But yes, I don't see why `worst` would be 0 - something to do with having `0` in the samples. It's a bug I guess.

**Comment by phpstatic** [comment]
The default `NothingBench` revs is too small with `gcc -O3` build php, this is my test apple os php vs my build php.

on my test , if `best` is 0, then `worst ` will always be 0.

```sh
/usr/bin/php /opt/web/bench/bin/phpbench run --report=aggregate --filter=NothingBench --revs=100
PhpBench @git_tag@. Running benchmarks.
Using configuration file: /opt/web/bench/phpbench.json.dist

\PhpBench\Benchmarks\Macro\benchmarks\NothingBench

    benchNothing............................I0 [μ Mo]/r: 0.050 0.050 (μs) [μSD μRSD]/r: 0.000μs 0.00%

1 subjects, 1 iterations, 100 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 0.050 [0.050 0.050] 0.050 (μs)
⅀T: 0.050μs μSD/r 0.000μs μRSD/r: 0.000%
suite: 1343b0fc33ff978bec3fbe2967b5e6b16e5be65b, date: 2020-02-07, stime: 14:27:00
+--------------+--------------+-----+------+-----+------------+---------+---------+---------+---------+---------+--------+-------+
| benchmark    | subject      | set | revs | its | mem_peak   | best    | mean    | mode    | worst   | stdev   | rstdev | diff  |
+--------------+--------------+-----+------+-----+------------+---------+---------+---------+---------+---------+--------+-------+
| NothingBench | benchNothing | 0   | 100  | 1   | 2,147,736b | 0.050μs | 0.050μs | 0.050μs | 0.050μs | 0.000μs | 0.00%  | 1.00x |
+--------------+--------------+-----+------+-----+------------+---------+---------+---------+---------+---------+--------+-------+
```

```sh
/usr/bin/php /opt/web/bench/bin/phpbench run --report=aggregate --filter=NothingBench --revs=100
PhpBench @git_tag@. Running benchmarks.
Using configuration file: /opt/web/bench/phpbench.json.dist

\PhpBench\Benchmarks\Macro\benchmarks\NothingBench

    benchNothing............................I0 [μ Mo]/r: 0.050 0.050 (μs) [μSD μRSD]/r: 0.000μs 0.00%

1 subjects, 1 iterations, 100 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 0.050 [0.050 0.050] 0.050 (μs)
⅀T: 0.050μs μSD/r 0.000μs μRSD/r: 0.000%
suite: 1343b0fc33ff978bec3fbe2967b5e6b16e5be65b, date: 2020-02-07, stime: 14:27:00
+--------------+--------------+-----+------+-----+------------+---------+---------+---------+---------+---------+--------+-------+
| benchmark    | subject      | set | revs | its | mem_peak   | best    | mean    | mode    | worst   | stdev   | rstdev | diff  |
+--------------+--------------+-----+------+-----+------------+---------+---------+---------+---------+---------+--------+-------+
| NothingBench | benchNothing | 0   | 100  | 1   | 2,147,736b | 0.050μs | 0.050μs | 0.050μs | 0.050μs | 0.000μs | 0.00%  | 1.00x |
+--------------+--------------+-----+------+-----+------------+---------+---------+---------+---------+---------+--------+-------+
```
